In [0]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
link = "https://drive.google.com/open?id=19o84Ph019PjY5TRMVWQrWqY5xiSI7iSN"

In [3]:
fluff, id = link.split('=')
print (id) # Verify that you have everything after '='

19o84Ph019PjY5TRMVWQrWqY5xiSI7iSN


In [0]:
import pandas as pd
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('dataset2.csv')  
df = pd.read_csv('dataset2.csv')
# Dataset is now stored in a Pandas Dataframe

In [5]:
df.head()

1    7    6  1.1  7.1  ...  115.292  16.672  139.280  114.289  0.2189
0    1    7    6    1    7  ...      115      16      139      114       0
1    1    7    6    1    7  ...      115      16      139      114       0
2  218  169  137  218  170  ...      186     243      218      186       0
3  218  169  137  218  170  ...      186     243      218      186       0
4  218  169  137  218  170  ...      186     243      218      186       0

[5 rows x 108001 columns]

In [6]:
output = '0.2189'
Y = df[output].values
print(Y)
print(len(Y))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 

In [7]:
df = df.drop(output,1)
print(df.head)

<bound method NDFrame.head of        1    7    6  1.1  7.1  ...  140.298  115.292  16.672  139.280  114.289
0      1    7    6    1    7  ...      140      115      16      139      114
1      1    7    6    1    7  ...      140      115      16      139      114
2    218  169  137  218  170  ...      218      186     243      218      186
3    218  169  137  218  170  ...      218      186     243      218      186
4    218  169  137  218  170  ...      218      186     243      218      186
..   ...  ...  ...  ...  ...  ...      ...      ...     ...      ...      ...
969  250  255  246  249  254  ...      153      125     102      149      122
970  250  255  246  249  254  ...      153      125     102      149      122
971  222  208  179  232  222  ...      111      100      52      115       99
972  222  208  179  232  222  ...      111      100      52      115       99
973  222  208  179  232  222  ...      111      100      52      115       99

[974 rows x 108000 columns]>


In [8]:
X = df.values
print(X)
print(len(X))

[[  1   7   6 ...  16 139 114]
 [  1   7   6 ...  16 139 114]
 [218 169 137 ... 243 218 186]
 ...
 [222 208 179 ...  52 115  99]
 [222 208 179 ...  52 115  99]
 [222 208 179 ...  52 115  99]]
974


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(779, 108000)
(195, 108000)
(779,)
(195,)


In [11]:
#check image shape
X_train[0].shape

(108000,)

In [0]:
#reshape data to fit model
X_train = X_train.reshape(779,240,150,3)
X_test = X_test.reshape(195,240,150,3)

In [0]:
X_train = X_train/255
X_test = X_test/255

In [14]:
from keras.utils import to_categorical
#one-hot encode target column
print(Y_train[0])
Y_train = to_categorical(Y_train)
Y_test = to_categorical(Y_test)
Y_train[0]

Using TensorFlow backend.


4


array([0., 0., 0., 0., 1.], dtype=float32)

In [15]:
print(Y_train)

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [0]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten,MaxPooling2D,Dropout
#create model
model = Sequential()
#add model layers
model.add(Conv2D(240, kernel_size=5, activation='relu', input_shape=(240,150,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(120, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(120, activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(5, activation='softmax'))

In [0]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [33]:
#train the model
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=20)

Train on 779 samples, validate on 195 samples
Epoch 1/20
779/779 [==============================] - 6s 8ms/step - loss: 2.8928 - acc: 0.2721 - val_loss: 1.5081 - val_acc: 0.4718
Epoch 2/20
779/779 [==============================] - 5s 6ms/step - loss: 1.4185 - acc: 0.3633 - val_loss: 1.4184 - val_acc: 0.3590
Epoch 3/20
779/779 [==============================] - 5s 6ms/step - loss: 1.2589 - acc: 0.5315 - val_loss: 1.0684 - val_acc: 0.5436
Epoch 4/20
779/779 [==============================] - 5s 6ms/step - loss: 0.9370 - acc: 0.6123 - val_loss: 0.7909 - val_acc: 0.6718
Epoch 5/20
779/779 [==============================] - 5s 6ms/step - loss: 0.6792 - acc: 0.7510 - val_loss: 0.7904 - val_acc: 0.6821
Epoch 6/20
779/779 [==============================] - 5s 6ms/step - loss: 0.4709 - acc: 0.8408 - val_loss: 0.4572 - val_acc: 0.8410
Epoch 7/20
779/779 [==============================] - 5s 6ms/step - loss: 0.2432 - acc: 0.9204 - val_loss: 0.2042 - val_acc: 0.9179
Epoch 8/20
779/779 [==========

In [35]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [36]:
cd /content/drive/'My Drive/'/FarmFrenzi

/content/drive/My Drive/FarmFrenzi


In [0]:
model.save('CNN.h5')